export const SHOW_ALL = 'show_all'
export const SHOW_LOCATION = 'show_location'
export const SHOW_VEHICLE = 'show_vehicle'
export const SHOW_WARDROBE = 'show_wardrobe'
export const SHOW_CAST = 'show_cast'
export const SHOW_STORYBOARD = 'show_storyboard'